### ISSUE TITLE
Extend use of IdentifiedDataSerializable

### ISSUE THREAD

**Issue by neilstevenson** [myawnhc/BankInABox#10]
Objects such as `Account` are `IdentifiedDataSerializable`

Others such as `RuleSetExecutor` and `CreditLimitCheck` are `java.io.Serializable`

All should ideally be `IdentifiedDataSerializable`, or at least those that are performance impacting

**Comment by myawnhc** [comment]
Have made most items IdentifiedJavaSerializable, will continue to look for opportunities to improve serialization as more types are added.
